### ISSUE TITLE
Provide support for different coverage tools

### ISSUE THREAD

**Issue by ChrisTimperley** [squaresLab/BugZoo#287]
Currently, BugZoo only provides the ability to compute coverage for C and C++ programs, and uses `gcov` to do so. Going forward, BugZoo needs to provide support for different languages (e.g., Java and Python), as well as alternative coverage tools for a particular language.

To add support for different coverage tools, we should introduce a new `CoverageExtractor` class, replacing the existing `CoverageManager`, which computes coverage using a particular tool (where each tool is implemented as a `CoverageExtractor` subclass). `CoverageExtractor` instances should be able to accept arguments to allow them to be customised to particular programs. For example, the `GcovExtractor` constructor may accept a list of files that should be instrumented.

## Internal API

Based on my experience of working with `gcov` and `coverage.py`, I propose that each `CoverageExtractor` implements the following methods:

* `prepare(container: Container) -> None`: instruments the source code, if necessary, and rebuilds the binary with the appropriate instrumentation, if needed.
* `cleanup(container: Container) -> None`: removes instrumentation from the source code, and rebuilds the binary without instrumentation.
* `extract(container: Container, from_files: Optional[List[str]]) -> FileLineSet`: reads any coverage files from disk (inside the container) before destroying those coverage files and returning the set of lines that were covered. If `from_files` is provided, coverage information will only be returned for the specified files. **(Is this ability really all that useful? This can be done in a single method call on the `FileLineSet` object.)**
* `coverage(container: Container, tests: Iterable[TestCase], *, instrument: bool = True) -> TestSuiteCoverage`: uses a given container to computes coverage information for a collection of tests. If `instrument` is set to `True`, the container will be instrumented and deinstrumented at the beginning and end of the call, respectively. Alternatively, if `instrument` is set to False, the container will be neither instrumented nor deinstrumented; it is assumed that the user has already instrumented the container.

## External API

All coverage-related methods exposed by the `ContainerManager` would remain the same. Users of BugZoo's Python library shouldn't need to change their code (or, if they're using the `CoverageManager` directly, the changes necessary should be minimal).

## Manifest File Format

In addition to replacing `CoverageManager` with `CoverageExtractor`, we will also need to modify the manifest file format to allow users to specify which coverage tool should be used along with any arguments that should be provided to that tool.

Below are some examples of what the revised `coverage` section might look like:

```
coverage:
  type: gcov
  files-to-instrument:
    - foo.c
```

```
coverage:
   type: coverage.py
```

```
coverage:
  type: cobertura
```

We need to decide what to do if a user doesn't provide a `coverage` section, or if there is no `type` property within the `coverage` section. One approach could be to associate a default coverage extractor type with each language (e.g., `gcov` for C and `coverage.py` for Python). If a language doesn't have a default coverage extractor, a warning could be raised to remind the user that coverage can't be computed for the given language; we could also throw a `CoverageNotSupportedForLanguage` exception if the user attempts to call any of the coverage-related methods exposed by the container manager.

## Runtime Dependencies

Currently, BugZoo assumes that `gcovr` is installed inside the container. Ideally, it shouldn't be necessary for the user to install their coverage tool of choice inside the container. Each `CoverageExtractor` could be optionally associated with a single `Plugin`, which is used to mount a set of portable libraries and binaries inside the container at launch. For example, `GCovExtractor` may be associated with a `gcovr` plugin which imports a portable, single-file `gcovr` binary into the container at `/opt/gcovr/bin/gcovr`.

## Roadmap

* [x] refactor core data structures to use `attrs` (#210)
* [x] add coverage instructions data structure
* [x] add hardcoded `CoverageExtractor` for `gcov`
* [x] remove server-side `CoverageManager` and fold logic into server-side `ContainerManager`
* [ ] rename `instrument` and `deinstrument` to `prepare` and `cleanup`.

**Comment by ChrisTimperley** [comment]
One issue with associating each `Bug` with a `CoverageExtractor` instance is that circular dependencies are then introduced (`CoverageExtractor -> ContainerManager -> CoverageExtractor`). To avoid this, it might be best to associate each `Bug` instance with a `CoverageInstructions` object, which could then be used to construct a `CoverageExtractor` (e.g., via `CoverageExtractor.from_instructions`).
